apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: hello-world
  description: Simple Hello World app deployed in Kubernetes
  tags:
    - hello
    - demo
spec:
  type: service
  lifecycle: production
  owner: user:guest